baseurl = "https://gilliganondata.com"
title = "Gilligan on Data"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
gtm_id= "GTM-MDWQCZC"
gtm_datalayer = "basic"

author = "Tim Wilson"
info = ["Analytics Curmudgeon","Perpetual Self-Doubter"]
description = "Miscellaneous musings and projects from a fellow who blogged regularly in the past, podcasts regularly now, and now occasionally scratches idle analysis itches."
keywords = "blog,analytics,personal"
avatarURL = "images/gilligan_oilpaint.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/gilliganondata/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 3
url = "https://twitter.com/tgwilson/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 3
url = "https://linkedin.com/in/tgwilson/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://gilliganondata.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Podcast"
weight = 2
url = "https://analyticshour.io"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true