baseURL = "https://gilliganondata.netlify.com"
languageCode = "en-us"
title = "Gilligan on Data"
theme = "hugo-theme-noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-2629617-13" 

# Add your Disqus shortname here.
# disqusShortname = ""    

# Files to ignore (recommended for blogdown)
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
  tag = "tags"

[author]
	name = "Tim Wilson"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Miscellaneous musings and projects from a fellow who blogged regularly in the past and now occasionally scratches idle analysis itches."

    showReadMore = false

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
  twitter = "https://twitter.com/tgwilson"
	instagram = "https://www.instagram.com/timwilson7/"
	linkedin = "https://www.linkedin.com/in/tgwilson/"

	# Programming
  github = "https://github.com/gilliganondata"
  
  # Highlights in Code
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

# Menu links along the sidebar navigation.
# [[menu.main]]
#	identifier = "about"
#	name = "About"
#	url = "/about/"
#	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

# [[menu.main]]
#	name = "Archives"
#	identifier = "archives"
#	url = "/archives/"
#	weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true