baseURL: https://gilliganondata.com
title: Gilligan on Data
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Tim Wilson
  avatarURL: images/gilligan_oilpaint.jpg
  colorScheme: auto
  gtm_id: GTM-MDWQCZC
  gtm_datalayer: basic
  commit: https://github.com/gilliganondata/gilliganondata_site
  csp:
    childsrc: '''self'''
    connectsrc:
      - '''self'''
    fontsrc:
      - '''self'''
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net/
    formaction: '''self'''
    framesrc: '''self'''
    imgsrc: '''self'''
    objectsrc: '''none'''
    prefetchsrc: '''self'''
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://fonts.googleapis.com/
      - https://cdn.jsdelivr.net/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Miscellaneous musings and projects from a fellow who blogged regularly in the past, podcasts regularly now, and now occasionally scratches idle analysis itches.
  hideColorSchemeToggle: no
  info:
    - Analytics Curmudgeo
    - Perpetual Self-Doubter
  keywords: blog,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2020
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/gilliganondata/
      weight: 1
    - icon: fa fa-2x fa-twitter
      name: Twitter
      url: https://twitter.com/tgwilson/
      weight: 3
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/tgwilson/
      weight: 4
    - icon: fa fa-2x fa-rss
      name: RSS
      rel: alternate
      type: application/rss+xml
      url: https://gilliganondata.com/index.xml
      weight: 6
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Podcast
          url: https://analyticshour.io
          weight: 2
        - name: Blog
          url: post/
          weight: 3
        - name: Projects
          url: projects/
          weight: 4
markup:
  goldmark:
    renderer:
      unsafe: true
