on:
  schedule:
    - cron: "0 * * * *"
    
jobs:
  generate-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install libcurl (for curl/httr)
        run: |
          sudo apt-get install libcurl4-openssl-dev -y

      - name: Install libmagick (for the magick package)
        run: |
          sudo apt-get install libmagick++-dev

      - name: Install R packages
        run: |
          install.packages(c("dplyr", "purrr", "httr", "knitr", "jpeg", "magick", "sketcher", "scales", "blogdown"), Ncpus = 2)
        shell: Rscript {0}

      - name: Generate Image
        env:
          SMUGMUG_KEY: ${{ secrets.SMUGMUG_KEY }}
          SMUGMUG_SECRET: ${{ secrets.SMUGMUG_SECRET }}
        run: |
          source("content/imgrandomize/R/master.R")
        shell: Rscript {0}

      - name: Build Site
        run: |
          blogdown::build_site(run_hugo = FALSE, 
                               build_rmd = TRUE)
        shell: Rscript {0}        
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "Add newly processed image"
          git push 